services:
  teletub:
    build: .
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx512m
    shm_size: 256mb
    networks:
      - omni

networks:
  omni:
    external: true
    name: omni-stack_omni